### ISSUE TITLE
Adding story and save it on MongoDB

### ISSUE THREAD

**Issue by Ansty93** [ProjectHackernewsGroup04/Backend#15]
Missing implementation of adding story and saving it into mongodb.

The story must be linked to the user.

**Comment by cph-cs241** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [III. ADD STORY - Medium](https://trello.com/c/Y7Crr5rE/6-iii-add-story-medium)

**Comment by cph-cs241** [comment]
As of now, it uses a helper method format_story() that ensures that the new story follows the items structure, but we might have to change this for further development concerning the kids, parent, etc. properties that points to another item(referencing).

**Comment by cph-cs241** [comment]
Made some revisions, now it returns the story itself instead of just a message: "Successfully added story".
